---

- name: Validate storage backend value
  fail: msg="Docker Registry storage backend specified ({{ docker_registry_storage_backend }}) not supported by this role yet."
  when: not docker_registry_storage_backend | match("local_fs|s3")

- include_tasks: "{{ docker_registry_storage_backend }}.yml"

